<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVbw68qp\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVbw68qp/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVbw68qp.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVbw68qp\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVbw68qp\appProdProjectContainer([
    'container.build_hash' => 'Vbw68qp',
    'container.build_id' => 'b5017075',
    'container.build_time' => 1554562050,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVbw68qp');
