<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPhna366\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPhna366/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerPhna366.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerPhna366\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerPhna366\appProdProjectContainer([
    'container.build_hash' => 'Phna366',
    'container.build_id' => '85b10536',
    'container.build_time' => 1554731934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPhna366');
